# Generated by Django 3.2.5 on 2021-10-04 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smnp_search', '0002_rename_auteur_categorie_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipement',
            name='ip',
            field=models.CharField(max_length=25, unique=True),
        ),
    ]
