# Generated by Django 3.2.5 on 2021-10-05 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smnp_search', '0005_alter_interface_idequipement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='idEquipement',
            field=models.CharField(max_length=40),
        ),
    ]
