# Generated by Django 3.2.5 on 2021-10-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smnp_search', '0006_alter_interface_idequipement'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interface',
            old_name='idEquipement',
            new_name='ip',
        ),
        migrations.AlterField(
            model_name='interface',
            name='oids',
            field=models.CharField(max_length=40),
        ),
    ]
