# Generated by Django 3.2.5 on 2021-10-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smnp_search', '0007_auto_20211005_1310'),
    ]

    operations = [
        migrations.AlterField(
            model_name='use',
            name='inOctect',
            field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name='use',
            name='outOctect',
            field=models.CharField(max_length=40),
        ),
    ]
