# Generated by Django 3.2.5 on 2021-10-05 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('smnp_search', '0008_auto_20211005_1347'),
    ]

    operations = [
        migrations.AlterField(
            model_name='interface',
            name='ip',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='interface',
            name='oids',
            field=models.IntegerField(),
        ),
    ]
