# Generated by Django 3.2.5 on 2021-10-21 10:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('smnp_search', '0010_auto_20211005_1401'),
    ]

    operations = [
        migrations.RenameField(
            model_name='use',
            old_name='inOctect',
            new_name='speedInOctect',
        ),
        migrations.RenameField(
            model_name='use',
            old_name='outOctect',
            new_name='speedOutOctect',
        ),
        migrations.AddField(
            model_name='interface',
            name='lastInOctect',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interface',
            name='lastOutOctect',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='interface',
            name='lastTimeTakeData',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Heure des dernieres donnees'),
        ),
        migrations.AddField(
            model_name='interface',
            name='speed',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
