# Generated by Django 3.2.5 on 2021-10-21 11:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smnp_search', '0011_auto_20211021_1244'),
    ]

    operations = [
        migrations.RenameField(
            model_name='interface',
            old_name='lastInOctect',
            new_name='lastInOctet',
        ),
        migrations.RenameField(
            model_name='interface',
            old_name='lastOutOctect',
            new_name='lastOutOctet',
        ),
    ]
