# Generated by Django 3.2.5 on 2021-10-21 11:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('smnp_search', '0012_auto_20211021_1306'),
    ]

    operations = [
        migrations.RenameField(
            model_name='use',
            old_name='speedInOctect',
            new_name='speedInOctet',
        ),
        migrations.RenameField(
            model_name='use',
            old_name='speedOutOctect',
            new_name='speedOutOctet',
        ),
    ]
